accounts/urls.py
from django.urls import path,reverse_lazy
from django.urls.conf import include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    # THIS was the normal authentication
    # path('login/',views.user_login,name='user_login'),

    # from django
    path('',views.dashboard,name='dashboard'),
    # register url
    path('register',views.register,name='register'),
    path('login/',auth_views.LoginView.as_view(),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('password_change/',auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('accounts:password_change_done')),name='password_change'),
    path('password_change/done/',auth_views.PasswordChangeDoneView.as_view(),name='password_change_done'),

    # password resets urls
    path('password_reset/',auth_views.PasswordResetView.as_view(success_url=reverse_lazy('accounts:password_reset_done')),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('accounts:password_reset_complete')),name='password_reset_confirm'),
    path('reset/done',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),

    # if you dont want to hard code authentication
    # path('',include('django.contrib.auth.urls')),
    # path('dashboard',views.dashboard,name='dashboard')

    # edit user profiles
    path('edit/',views.edit,name='edit'),
]

postgram/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('posts/',include('posts.urls',namespace='posts')),
    # path('bookmarks/',include('bookmarks.urls'))
    # path('social_auth/',include('social_django.urls',namespace='social'))
    # path('accounts/',include('django.contrib.auth.urls',namespace='accounts'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('create',views.post_create,name='create'),
    path('detail/<int:id>/<slug:slug>',views.post_detail,name='post_detail'),
    path('like',views.post_like,name='like'),
    path('',views.post_list,name='post_list'),
    path('users',views.user_list,name='user_list'),
    path('user/follow',views.user_follow,name='user_follow'),
    path('users/<username>',views.user_detail,name='user_detail'),
    
]

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model

# Create your models here.

class Profile(models.Model):
    """Extended user models"""

    user = models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)

    date_of_birth = models.DateField(blank=True,null=True)

    photo = models.ImageField(upload_to='users/%Y/%m/%d',blank=True)

    def __str__(self):
        return f"Profile for {self.user.username} created"

class Contact(models.Model):
    user_from = models.ForeignKey('auth.User',related_name='rel_from_set',on_delete=models.CASCADE)

    user_to = models.ForeignKey('auth.User',related_name='rel_to_set',on_delete=models.CASCADE)

    created = models.DateTimeField(auto_now_add=True,db_index=True)


    class Meta:
        ordering = ['-created',]

    def __str__(self):
        return f"{self.user_from} follows {self.user_to}"


# add following field to user dynamically
user_model = get_user_model()

user_model.add_to_class('following',models.ManyToManyField('self',through=Contact,related_name='followers',symmetrical=False))

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile
# from django.forms import fields

# HARD CODING login form
# class LoginForm(forms.Form):
#     """A form to authenticate users"""

#     username = forms.CharField()
#     password = forms.CharField(widget=forms.PasswordInput)

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput,label='Password')

    password2 = forms.CharField(label='Repeat password',widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('first_name','last_name','email','username')

    def clean_password2(self):
        """Check exactness of passwords"""
        data = self.cleaned_data

        if data['password'] != data['password2']:
            raise forms.ValidationError("Passwords didn't match")

        return data['password2']
       
class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username','first_name','last_name','email')

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('date_of_birth','photo')

accounts/views.py
from django.shortcuts import redirect, render
# from django.http import HttpResponse
# from django.contrib.auth import authenticate,login
# from .forms import LoginForm
from django.contrib.auth.decorators import login_required
from .forms import UserRegistrationForm,UserEditForm,ProfileEditForm
from .models import Profile
from django.contrib import messages

# Create your views here.
# superuser
# username: shanas
# password:postgram

# --user 2--
# username:nassibu
# password:nassibu123

# --user 3--
# username:mteua
# password:mteua123

@login_required
def dashboard(request):
    """Typical home view"""
    return render(request,'accounts/dashboard.html',{'section':'dashboard'})

def register(request):
    """Register new users to the app"""
    if request.method == 'POST':
        user_form = UserRegistrationForm(data=request.POST)

        if user_form.is_valid():
            # create a new user but dont save yet to db
            new_user = user_form.save(commit=False)

            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            # creates an empty profile for each user registered
            Profile.objects.create(user=new_user)

            return render(request,'accounts/register_done.html',{'new_user':new_user})

    else:
        user_form = UserRegistrationForm()

    return render(request,'accounts/register.html',{'user_form':user_form})

@login_required
def edit(request):
    """Allow users to edit their profile details"""
    if request.method == 'POST':
        # inorder to prepopulate the input fields with
        # previous objects user instance parameter
        # in the forms instances
        user_form = UserEditForm(instance=request.user,data=request.POST)

        profile_form = ProfileEditForm(instance=request.user.profile,data=request.POST,files=request.FILES)

        if user_form.is_valid and profile_form.is_valid:
            user_form.save()
            profile_form.save()
            messages.success(request,'Profile edited successfully')

        else:
            messages.error(request,'Error in updating your profile')

    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)

    return render(request,'accounts/edit.html',{'user_form':user_form,'profile_form':profile_form})



# def user_login(request):
#     """Authenticating users and starting a session"""
#     if request.method == 'POST':
#         form = LoginForm(data=request.POST)
        
#         if form.is_valid():
#             clean_data = form.cleaned_data
#             user = authenticate(request,username=clean_data['username'],password=clean_data['password'])

#             if user is not None:
#                 if user.is_active:
#                     login(request,user)
#                     return HttpResponse('Authenticated successfully')
#                 else:
#                     return HttpResponse('disabled account')

#             else:
#                 return HttpResponse('Invalid login')

#     else:
#         form = LoginForm()

#     return render(request,'accounts/login.html',{'form':form})

templates/accounts/dashboard.html
{% extends 'base.html' %}
{% block title %}Dashboard{% endblock title %}

{% block content %}
    <h1>Dashboard</h1>
    {% with total_post_created=request.user.post_created.count  %}
        <p>Welcome to your dashboard you've created {{ total_post_created}} post{{ total_post_created|pluralize}}</p>
    {% endwith %}
    <p>You can <a href="{% url 'accounts:edit'%}">edit</a> your profile or <a href="{% url 'accounts:password_change' %}">change your password</a></p>
    <a href="{% url 'posts:create'%}">Post</a>
{% endblock content %}

templates/accounts/edit.html
{% extends 'base.html' %}
{% block title %} Edit Profile {% endblock title %}

{% block content %}
    <h1>Edit your account</h1>
    {% if user_form.errors and profile_form.errors %}
        <p>Failed to update</p>

    {% else %}
        <form action="" method="post" enctype="multipart/form-data">
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Edit">
        </form>
    {% endif %}
 
    
{% endblock content %}

templates/accounts/login.html
{% extends 'base.html' %} 
{% block title %} Log In {% endblock %} 
{% block content%}
<h1>Log In</h1>
<form action="" method="post">
  {{ form.as_p }} 
  {% csrf_token %}
  <input type="submit" value="Log In" />
</form>
{% endblock content %}

templates/accounts/register.html
{% extends 'base.html' %}
{% block title %}Register{% endblock title %}

{% block content %}
    <h1>Register using this form</h1>
    <form action="" method="post">
        {{ user_form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Register">
    </form>
{% endblock content %}

templates/accounts/register_done.html
{% extends 'base.html' %}
{% block title %}Success{% endblock title %}

{% block content %}
    {% if new_user %}
        <h1>Successfully registered you can <a href="{% url 'accounts:login'%}">Log In</a></h1>

    {% else %}
        <h1>Sorry, Try again the username exists</h1>
    {% endif %}
{% endblock content %}