accounts/urls.py
from django.urls import path,reverse_lazy
from django.urls.conf import include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    # THIS was the normal authentication
    # path('login/',views.user_login,name='user_login'),

    # from django
    path('',views.dashboard,name='dashboard'),
    # register url
    path('register',views.register,name='register'),
    path('login/',auth_views.LoginView.as_view(),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('password_change/',auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('accounts:password_change_done')),name='password_change'),
    path('password_change/done/',auth_views.PasswordChangeDoneView.as_view(),name='password_change_done'),

    # password resets urls
    path('password_reset/',auth_views.PasswordResetView.as_view(success_url=reverse_lazy('accounts:password_reset_done')),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('accounts:password_reset_complete')),name='password_reset_confirm'),
    path('reset/done',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),

    # if you dont want to hard code authentication
    # path('',include('django.contrib.auth.urls')),
    # path('dashboard',views.dashboard,name='dashboard')

    # edit user profiles
    path('edit/',views.edit,name='edit'),
]

postgram/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('posts/',include('posts.urls',namespace='posts')),
    # path('bookmarks/',include('bookmarks.urls'))
    # path('social_auth/',include('social_django.urls',namespace='social'))
    # path('accounts/',include('django.contrib.auth.urls',namespace='accounts'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('create',views.post_create,name='create'),
    path('detail/<int:id>/<slug:slug>',views.post_detail,name='post_detail'),
    path('like',views.post_like,name='like'),
    path('',views.post_list,name='post_list'),
    path('users',views.user_list,name='user_list'),
    path('user/follow',views.user_follow,name='user_follow'),
    path('users/<username>',views.user_detail,name='user_detail'),
    
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}PostGram{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'accounts/css/base.css' %}" />
  </head>
  <body>
    <div id="header">
      <span class="logo">PostGram</span>
      {% if request.user.is_authenticated %}
        <ul class="menu">
          <li {% if section == 'dashboard'%}class="selected" {% endif %}>
            <a href="{% url 'accounts:dashboard' %}">Dashboard</a>
          </li>
          <li {% if section == 'images'%}class="selected" {% endif %}>
            <a href="{% url 'posts:post_list' %}">Images</a>
          </li>
          <li {% if section == 'people'%}class="selected" {% endif %}>
            <a href="{% url 'posts:user_list' %}">People</a>
          </li>
        </ul>
      {% endif %}
      <span class="user">
        {% if request.user.is_authenticated %}
          Hello {{ request.user.username }}, <a href="{% url 'accounts:logout' %}">Log Out</a>
          {% else %}
          <a href="{% url 'accounts:login' %}">Log In</a>
        {% endif %}
      </span>
    </div>
    {% if messages %}
      <ul class="messages">
        {% for message in messages %}
          <li class="{{ message.tags}}">{{ message|safe}}<a href="#" class="close">X</a></li>
        {% endfor %}
      </ul>
    {% endif %}
    <div id="content">{% block content%} {% endblock content %}</div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/
jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js"></script>
<script>
  const csrftoken = Cookies.get('csrftoken');
  const csrfSafeMethod = (method)=>{
    // these HTTP methods do not require csrf protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
  }
  $.ajaxSetup({
    beforeSend:function(xhr,settings){
      if(!csrfSafeMethod(settings.type)&&!this.crossDomain){
        xhr.setRequestHeader("X-CSRFToken",csrftoken);
      }
    }
  })
  $(document).ready(function(){
    {% block domready %}{% endblock domready %}
  });
</script>
  </body>
</html>