postgram/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('posts/',include('posts.urls',namespace='posts')),
    # path('bookmarks/',include('bookmarks.urls'))
    # path('social_auth/',include('social_django.urls',namespace='social'))
    # path('accounts/',include('django.contrib.auth.urls',namespace='accounts'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('create',views.post_create,name='create'),
    path('detail/<int:id>/<slug:slug>',views.post_detail,name='post_detail'),
    path('like',views.post_like,name='like'),
    path('',views.post_list,name='post_list'),
    path('users',views.user_list,name='user_list'),
    path('user/follow',views.user_follow,name='user_follow'),
    path('users/<username>',views.user_detail,name='user_detail'),
    
]

posts/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse

# Create your models here.
class Post(models.Model):
    """Allow users to post pictures"""
    title = models.CharField(max_length=200,blank=True,null=True)

    user = models.ForeignKey(to=settings.AUTH_USER_MODEL,related_name='post_created',on_delete=models.CASCADE)

    slug = models.SlugField(max_length=500,blank=True)

    caption = models.TextField(blank=True,null=True)

    image = models.ImageField(upload_to='posts/%Y/%m/%d')

    created = models.DateTimeField(auto_now_add=True)

    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,related_name='post_liked',blank=True)

    def get_absolute_url(self):
        return reverse("posts:post_detail", args=[self.id,self.slug])
    
    class Meta:
        ordering = ['-created',]

    def __str__(self):
        return f"{self.title} by {self.user}"

    def save(self,*args,**kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args,**kwargs)

posts/forms.py
from django import forms
from .models import Post
from django.utils.text import slugify


class PostCreateForm(forms.ModelForm):
    """A form to manage the posts by users"""

    class Meta:
        model = Post

        fields = ['title','image','caption',]
        
    # def save(self,force_insert=False,force_update=False,commit=True):
    #     post = super().save(commit=False)
    #     post_name = self.cleaned_data['image']
    #     title = slugify(post.title)
    #     ext = post_name.rsplit('.',1)[1].lower()
    #     name = f"{title}.{ext}"
    #     post.image = name

    #     if commit:
    #         post.save()
    #     return post

        

posts/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import PostCreateForm
from .models import Post
from accounts.models import Contact
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from common.decorators import ajax_required
from django.contrib.auth.models import User

# Create your views here.
@login_required
def post_create(request):
    """Enable users create posts"""
    if request.method != 'POST':
        form = PostCreateForm()

    else:
        form = PostCreateForm(data=request.POST,files=request.FILES)
        print(form.is_valid())

        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            print(new_form.user)
            new_form.save()
            return redirect('accounts:dashboard')

    return render(request,'posts/create.html',{'form':form})

@login_required
def post_detail(request,id,slug):
    """Show the post detail to users"""
    post = get_object_or_404(Post,id=id,slug=slug)
    return render(request,'posts/detail.html',{'section':'images','post':post})

@login_required
@require_POST
@ajax_required
def post_like(request):
    """Allow users to like post through AJAX"""
    post_id = request.POST.get('id')
    action = request.POST.get('action')

    if post_id and action:
        try:
            post = Post.objects.get(id=post_id)
            if action == 'like':
                post.users_like.add(request.user)
            else:
                post.users_like.remove(request.user)
            return JsonResponse({'status':'ok'})
        except:
            pass
    return JsonResponse({'status':'error'})

@login_required
def post_list(request):
    """Display users post"""
    posts = Post.objects.filter(user=request.user)

    return render(request,'posts/list.html',{'section':'images','posts':posts})

@login_required
def user_list(request):
    """Display all the users"""
    users = User.objects.filter(is_active=True)
    return render(request,'posts/user/list.html',{'section':'people','users':users})

@login_required
def user_detail(request,username):
    """Display user details"""
    user = get_object_or_404(User,username=username,is_active=True)

    # posts = Post.objects.filter(user=request.user)

    return render(request,'posts/user/detail.html',{'section':'people','user':user})

@ajax_required
@require_POST
@login_required
def user_follow(request):
    """Allow users to follow each other"""
    user_id = request.POST.get('id')
    action = request.POST.get('action')
    if user_id and action:
        try:
            user = User.objects.get(id=user_id)
            if action == 'follow':
                Contact.objects.get_or_create(user_from=request.user,user_to=user)
            else:
                Contact.objects.filter(user_from=request.user,user_to=user).delete()
            return JsonResponse({'status':'ok'})
        except User.DoesNotExist:
            return JsonResponse({'status':'error'})
    return JsonResponse({'status':'error'})

templates/posts/user/detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}{{ user.username }}{% endblock title %}
{% block content %}
    <h1>{{ user.username }}</h1>
    <div class="profile-info">
        <img src="{% thumbnail user.profile.photo 180x180 %}" alt="" class="user-detail">
    </div>
    {% with total_followers=user.followers.count %}
        <span class="count">
            <span class="total">
                {{ total_followers }}
            </span>
            follower{{ total_followers|pluralize }}
        </span>
        <a href="#" 
        data-id="{{ user.id }}" 
        data-action="{% if request.user in user.followers.all %}un{% endif%}follow" 
        class="follow button"
        >
        {% if request.user not in user.followers.all %}
            Follow
            {% else %}
            Unfollow
        {% endif %}
        </a>
   
    {% endwith %}
{% endblock content %}
{% block domready %}
        $('a.follow').click(function(e){
            e.preventDefault();
            $.post("{% url 'posts:user_follow' %}",{
                id:$(this).data('id'),
                action:$(this).data('action')
            },
            function(data){
                if(data['status'] == 'ok'){
                    var previousAction = $('a.follow').data('action');

                    // toggle data-action
                    $('a.follow').data('action',previousAction == 'follow'?'unfollow':'follow');
                    // toggle link text
                    $('a.follow').text(previousAction == 'follow'?'Unfollow':'Follow');
                    // update total followers
                    var previousFollowers = parseInt($('span.count .total').text());
                    $('span.count .total').text(previousAction=='follow'?previousFollowers+1:previousFollowers-1);
                }
            })
        })
{% endblock domready %}

templates/posts/user/list.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}People{% endblock title %}

{% block content %}
    <h1>People</h1>
    <div id="people-list">
        {% for user in users %}
            <div class="user">
                <a href="{{ user.get_absolute_url }}">
                    <img src="{% thumbnail user.profile.photo 180x180 %}" alt="">
                </a>
                <div class="info">
                    <a href="{{ user.get_absolute_url }}">
                        {{ user.username }}
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}